# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 05:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('creator_user_id', models.CharField(max_length=255)),
                ('last_updated_user_id', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=12)),
                ('owner_name', models.CharField(blank=True, max_length=12)),
                ('owner_contact_number', models.CharField(blank=True, max_length=12)),
                ('tenant_name', models.CharField(blank=True, max_length=12)),
                ('tenant_phone', models.CharField(blank=True, max_length=12)),
                ('tenant_email', models.CharField(blank=True, max_length=12)),
                ('owner_email', models.CharField(blank=True, max_length=12)),
                ('follow_up_owner_needed', models.BooleanField(default=False)),
                ('land_bank_property', models.BooleanField(default=False)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_user_id', models.CharField(max_length=255)),
                ('last_updated_user_id', models.CharField(max_length=255)),
                ('crossed_out', models.BooleanField(default=False)),
                ('date_updated', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('gang_related', models.BooleanField(default=False)),
                ('img', models.CharField(blank=True, max_length=1000)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('racially_motivated', models.BooleanField(default=False)),
                ('square_footage', models.CharField(blank=True, max_length=50)),
                ('surface', models.CharField(blank=True, max_length=100)),
                ('tag_words', models.CharField(blank=True, max_length=255)),
                ('tag_initials', models.CharField(blank=True, max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Address')),
            ],
        ),
        migrations.DeleteModel(
            name='TaggingPoint',
        ),
    ]
