# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("backend", "0002_auto_20171130_0512")]

    operations = [
        migrations.AddField(
            model_name="address",
            name="type_of_property",
            field=models.IntegerField(default=False),
        )
    ]
