# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-03 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20180111_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='type_of_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PropertyType'),
        ),
    ]
