# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-30 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20180703_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='type_name',
            field=models.CharField(max_length=255),
        ),
    ]
