# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_contacttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttype',
            name='slug',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
