# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("backend", "0010_auto_20190209_0250")]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=25, unique=True),
        )
    ]
