# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20190209_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='type_of_property',
        ),
        migrations.AddField(
            model_name='address',
            name='property_type',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.PropertyType'),
            preserve_default=False,
        ),
    ]
